### ISSUE TITLE
QueryId in pull query

### ISSUE THREAD

**Issue by Frosin** [rmoff/ksqldb-go#1]
Hello! With all correct pull requests, I get log: `(Query ID not found - this is expected for a pull query)`, this is due to the fact that I always have queryId == nil, is this incorrect behavior?
https://github.com/rmoff/ksqldb-go/blob/master/pull.go#L97

**Comment by rmoff** [comment]
I'm not sure I quite follow your question. There is no query ID for pull queries, and that's what the log message is telling you.

**Comment by Frosin** [comment]
Thanks for your reply! I think I get it. But this code https://github.com/rmoff/ksqldb-go/blob/master/pull.go#L94-L98 is relevant for push requests but redundant for pull requests?

**Comment by rmoff** [comment]
It's applicable to both, but handles the fact that there's no query ID in the header for pull queries.

**Comment by rmoff** [comment]
Please close this if this all makes sense to you :)

**Comment by Frosin** [comment]
If the absence of queryId is not an error, why log this message to stdout? Maybe you should consider disabling debug logging?

**Comment by rmoff** [comment]
Sounds good - submit a PR?

**Comment by rmoff** [comment]
https://github.com/rmoff/ksqldb-go/pull/2

**Comment by rmoff** [comment]
Closed with #11
